FROM apache/airflow:2.10.5-python3.11

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends default-jre-headless && \
    rm -rf /var/lib/apt/lists/*
USER airflow

COPY requirements.txt /tmp/project-requirements.txt

RUN pip install --no-cache-dir \
    -r /tmp/project-requirements.txt \
    --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.10.5/constraints-3.11.txt